version: "3.8"
services:
  client:
    image: lexiclean-client
    build: ./client/
    stdin_open: true
    ports:
      - "3000:3000"
    networks:
      - lexiclean-app
    volumes:
      - ./client/:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - server
  server:
    image: lexiclean-server
    build: ./server/
    stdin_open: true
    ports:
      - "3001:3001"
    networks:
      - lexiclean-app
    volumes:
      - ./server/:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongo
  mongo:
    image: mongo:4.4.8
    ports:
      - "27018:27017"
    networks:
      - lexiclean-app
    volumes:
      - mongo-data:/data/db

networks:
  lexiclean-app:
    driver: bridge

volumes:
  mongo-data:
    driver: local