name: CI

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ["20.x"] # Use the latest patch version of Node 20

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm" # Enabling caching for npm

      - name: Install backend dependencies
        working-directory: ./backend
        run: npm install

      - name: Test backend
        working-directory: ./backend
        run: npm test

      - name: Install client dependencies
        working-directory: ./client
        run: npm install

      - name: Test client
        working-directory: ./client
        run: npm test
